export const GET_PUBLICATIONS_LOAD="GET_PUBLICATIONS_LOAD";
export const GET_PUBLICATIONS_SUCCESS="GET_PUBLICATIONS_SUCCESS";
export const GET_PUBLICATIONS_FAILED="GET_PUBLICATIONS_FAILED";




export const DELETE_PUBLICATION = "DELETE_PUBLICATION";
// get contact by id
export const GET_PUBLICATION = "GET_PUBLICATION";

// post contact
export const POST_PUBLICATION = "POST_PUBLICATION";
export const EDIT_PUBLICATION = "EDIT_PUBLICATION";
